### ISSUE TITLE
关于实验部分的模型问题

### ISSUE THREAD

**Issue by MING-ZCH** [haidequanbu/ESC-Eval#1]
hi~great work！
我是EmoLLM的主要开发者，想询问一下论文中实验部分使用的EmoLLM是哪一个版本？
![image](https://github.com/haidequanbu/ESC-Eval/assets/119648793/ad36f335-6949-4b51-ae32-da8db72f19e4)

**Comment by haidequanbu** [comment]
Hey, thanks for your issue.
The EmoLLM under evaluation is based on InternLM2, where we downloaded from [https://openxlab.org.cn/models/detail/jujimeizuo/EmoLLM_Model](url)
![image](https://github.com/haidequanbu/ESC-Eval/assets/67882439/f252f4dd-addc-4515-be47-7fb9fa351f6b)

**Comment by MING-ZCH** [comment]
Thanks！感谢你们的使用和支持~
这是EmoLLM V1.0版本，欢迎实测EmoLLM V2.0版本，效果会更好！
EmoLLM V2.0: https://github.com/SmartFlowAI/EmoLLM/blob/main/xtuner_config/internlm2_chat_7b_full.py

**Comment by haidequanbu** [comment]
谢谢提醒～
完成实验可能需要一定的周期，我们也在优化评估的自动化流程，优化完成后，我们会统一更新结果！
再次感谢提醒！
