### ISSUE TITLE
关于实验部分的训练数据

### ISSUE THREAD

**Issue by c1player** [haidequanbu/ESC-Eval#2]
你好，训练ESC-val使用到了通用的role-playing数据和ESC数据，想问一下这些通用的role-playing数据有哪些，也是包含role-card和多轮对话吗，感谢！

**Comment by haidequanbu** [comment]
谢谢你的兴趣，通用的role-palying的数据主要是在huggingface上找到的，其中单论和多轮都有。其中不一定包含角色卡。形式有几种，列举如下：
1. 我希望你扮演韦小宝与他人对话。
2. 我希望你扮演xxx与他人对话，xxx的角色描述如下：xxxxxx。
主要是看原数据集有什么内容。
推荐几个数据集，可能需要自己处理下：
1. https://huggingface.co/datasets/Minami-su/roleplay_multiturn_chat_1k_zh_v0.1
2. https://huggingface.co/datasets/silk-road/Haruhi-Baize-Role-Playing-Conversation
